name: lanviz_client_repository
description: Client repository for LanViz
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  web_socket_channel: ^2.4.0
  network_info_plus: ^4.1.0
  json_serializable: ^6.7.1
