name: lanviz_network
description: shared package containing models used by the lanviz_server and lanviz_client packages
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
